#!/bin/sh

export SSL_CERT_FILE="{{pkgPathFor "core/cacerts"}}/ssl/cert.pem"

cd {{pkg.path}}

while true; do
  if [ $SECONDS -gt {{cfg.interval}} ]; then
    SECONDS=0
    chef-client -z -l {{cfg.log_level}} -c {{pkg.svc_config_path}}/client-config.rb -j {{pkg.svc_config_path}}/attributes.json --once --no-fork --run-lock-timeout {{cfg.run_lock_timeout}}
  fi
  sleep 1
done
